### ISSUE TITLE
Column and page annotations as properties of line annotation

### ISSUE THREAD

**Issue by kuczera** [THM-Graphs/atag-editor#2]
Add properties 

- firstLineOfColumn 
- lastLineOfColumn 
- firstLineOfPage 
- lastLineOfPage 

to the line annotation.

The column and page annotations will be calculated later.

**Comment by mmiche01** [comment]
Done in commi [7b11124d0dfcb937261434a0210c11b71638c762](https://github.com/THM-Graphs/atag-editor/commit/7b11124d0dfcb937261434a0210c11b71638c762)
